"""Stable audit action codes independent of display language."""

LOGIN_SUCCEEDED = "authentication.login_succeeded"
LOGIN_FAILED = "authentication.login_failed"
LOGIN_LOCKED = "authentication.login_locked"
LOGOUT = "authentication.logout"
PASSWORD_CHANGED = "account.password_changed"
PASSWORD_RESET = "account.password_reset"
ACCOUNT_CREATED = "account.created"
ACCOUNT_UPDATED = "account.updated"
ACCOUNT_DEACTIVATED = "account.deactivated"
ACCOUNT_REACTIVATED = "account.reactivated"
LANGUAGE_CHANGED = "account.language_changed"
DEPARTMENT_CREATED = "department.created"
DEPARTMENT_UPDATED = "department.updated"
DEPARTMENT_ARCHIVED = "department.archived"
DEPARTMENT_RESTORED = "department.restored"
