"""Localized presentation for stable audit codes."""

from typing import Final

from django.utils.translation import gettext_lazy as _

from apps.audit import actions

ACTION_LABELS: Final = {
    actions.LOGIN_SUCCEEDED: _("Login succeeded"),
    actions.LOGIN_FAILED: _("Login failed"),
    actions.LOGIN_LOCKED: _("Login temporarily locked"),
    actions.LOGOUT: _("Logout"),
    actions.PASSWORD_CHANGED: _("Password changed"),
    actions.PASSWORD_RESET: _("Password reset"),
    actions.ACCOUNT_CREATED: _("Account created"),
    actions.ACCOUNT_UPDATED: _("Account updated"),
    actions.ACCOUNT_DEACTIVATED: _("Account deactivated"),
    actions.ACCOUNT_REACTIVATED: _("Account reactivated"),
    actions.LANGUAGE_CHANGED: _("Language preference changed"),
    actions.DEPARTMENT_CREATED: _("Department created"),
    actions.DEPARTMENT_UPDATED: _("Department updated"),
    actions.DEPARTMENT_ARCHIVED: _("Department archived"),
    actions.DEPARTMENT_RESTORED: _("Department restored"),
    actions.PROJECT_CREATED: _("Project created"),
    actions.PROJECT_UPDATED: _("Project updated"),
    actions.PROJECT_STATUS_CHANGED: _("Project status changed"),
    actions.PROJECT_ARCHIVED: _("Project archived"),
    actions.PROJECT_RESTORED: _("Project restored"),
    actions.PROJECT_TEAM_UPDATED: _("Project team updated"),
    actions.CLIENT_CREATED: _("Client created"),
    actions.CLIENT_UPDATED: _("Client updated"),
    actions.CLIENT_ARCHIVED: _("Client archived"),
    actions.CLIENT_RESTORED: _("Client restored"),
    actions.CATEGORY_CREATED: _("Category created"),
    actions.CATEGORY_UPDATED: _("Category updated"),
    actions.CATEGORY_ARCHIVED: _("Category archived"),
    actions.CATEGORY_RESTORED: _("Category restored"),
    actions.COURSE_CREATED: _("Course created"),
    actions.COURSE_UPDATED: _("Course updated"),
    actions.COURSE_STATUS_CHANGED: _("Course status changed"),
    actions.COURSE_ARCHIVED: _("Course archived"),
    actions.COURSE_RESTORED: _("Course restored"),
    actions.COURSE_TRAINERS_UPDATED: _("Course trainers updated"),
    actions.COURSE_FILE_UPLOADED: _("Course file uploaded"),
    actions.TRAINER_CREATED: _("Trainer created"),
    actions.TRAINER_UPDATED: _("Trainer updated"),
    actions.TRAINER_ARCHIVED: _("Trainer archived"),
    actions.TRAINER_RESTORED: _("Trainer restored"),
    actions.TASK_CREATED: _("Task created"),
    actions.TASK_UPDATED: _("Task updated"),
    actions.TASK_STATUS_CHANGED: _("Task status changed"),
    actions.TASK_ARCHIVED: _("Task archived"),
    actions.TASK_RESTORED: _("Task restored"),
    actions.TASK_ASSIGNMENTS_UPDATED: _("Task assignments updated"),
    actions.TASK_TAGS_UPDATED: _("Task tags updated"),
    actions.TASK_COMMENT_ADDED: _("Task comment added"),
    actions.TASK_FILE_UPLOADED: _("Task file uploaded"),
    actions.TAG_CREATED: _("Tag created"),
    actions.TAG_UPDATED: _("Tag updated"),
    actions.TAG_ARCHIVED: _("Tag archived"),
    actions.TAG_RESTORED: _("Tag restored"),
    actions.MILESTONE_CREATED: _("Milestone created"),
    actions.MILESTONE_UPDATED: _("Milestone updated"),
    actions.MILESTONE_ARCHIVED: _("Milestone archived"),
    actions.MILESTONE_RESTORED: _("Milestone restored"),
    actions.APPROVAL_SUBMITTED: _("Approval submitted"),
    actions.APPROVAL_APPROVED: _("Approval approved"),
    actions.APPROVAL_REJECTED: _("Approval rejected"),
    actions.TRAINEE_ENROLLED: _("Trainee enrolled"),
    actions.TRAINEE_UPDATED: _("Trainee updated"),
    actions.TRAINEE_ARCHIVED: _("Trainee archived"),
    actions.TRAINEE_RESTORED: _("Trainee restored"),
    actions.TRAINEE_IMPORT_PREVIEWED: _("Trainee import previewed"),
    actions.TRAINEE_IMPORT_CONFIRMED: _("Trainee import confirmed"),
    actions.TRAINEE_IMPORT_CANCELLED: _("Trainee import cancelled"),
    actions.SESSION_CREATED: _("Session created"),
    actions.SESSION_ARCHIVED: _("Session archived"),
    actions.TRAINER_LINK_ISSUED: _("Trainer link issued"),
    actions.ATTENDANCE_SUBMITTED: _("Attendance submitted"),
    actions.ATTENDANCE_RESUBMITTED: _("Attendance resubmitted"),
    actions.ATTENDANCE_APPROVED: _("Attendance approved"),
    actions.ATTENDANCE_REJECTED: _("Attendance rejected"),
    actions.ATTENDANCE_CORRECTED: _("Attendance corrected"),
    actions.NOTIFICATION_PREFERENCES_UPDATED: _("Notification preferences updated"),
    actions.AUDIT_EXPORTED: _("Audit exported"),
    actions.BACKUP_STATUS_RECORDED: _("Backup status recorded"),
    actions.RESTORE_TEST_STATUS_RECORDED: _("Restore test status recorded"),
    actions.RETENTION_INVENTORY_RECORDED: _("Retention inventory recorded"),
    actions.AI_BRIEFING_REQUESTED: _("AI briefing requested"),
    actions.AI_BRIEFING_COMPLETED: _("AI briefing completed"),
    actions.AI_BRIEFING_FAILED: _("AI briefing failed"),
    actions.AI_BRIEFING_REVIEWED: _("AI briefing reviewed"),
    actions.EXECUTIVE_REPORT_REQUESTED: _("Executive report requested"),
    actions.EXECUTIVE_REPORT_COMPLETED: _("Executive report completed"),
    actions.EXECUTIVE_REPORT_FAILED: _("Executive report failed"),
    actions.EXECUTIVE_REPORT_DOWNLOADED: _("Executive report downloaded"),
    actions.CRITICAL_ALERT_DELIVERED: _("Critical task alert delivered"),
    actions.AGENT_RUN_REQUESTED: _("Project-agent run requested"),
    actions.AGENT_RUN_AWAITING_APPROVAL: _("Project-agent run awaiting approval"),
    actions.AGENT_RUN_COMPLETED: _("Project-agent run completed"),
    actions.AGENT_RUN_FAILED: _("Project-agent run failed"),
    actions.AGENT_RUN_CANCELLED: _("Project-agent run cancelled"),
    actions.AGENT_RUN_REVIEWED: _("Project-agent run reviewed"),
    actions.AGENT_TOOL_COMPLETED: _("Project-agent tool completed"),
    actions.AGENT_TOOL_FAILED: _("Project-agent tool failed safely"),
    actions.AGENT_PROPOSAL_CREATED: _("Project-agent proposal created"),
    actions.AGENT_PROPOSAL_APPROVED: _("Project-agent proposal approved"),
    actions.AGENT_PROPOSAL_REJECTED: _("Project-agent proposal rejected"),
    actions.AGENT_PROPOSAL_EXECUTED: _("Project-agent proposal executed"),
    actions.AGENT_PROPOSAL_STALE: _("Project-agent proposal became stale"),
    actions.AGENT_PROPOSAL_FAILED: _("Project-agent proposal failed safely"),
    actions.AGENT_PROPOSAL_EXPIRED: _("Project-agent proposal expired"),
}

TARGET_TYPE_LABELS: Final = {
    "account": _("Account"),
    "approval_request": _("Approval"),
    "audit_export": _("Audit export"),
    "authentication": _("Authentication"),
    "backup": _("Backup"),
    "category": _("Category"),
    "client": _("Client"),
    "course": _("Course"),
    "department": _("Department"),
    "enrollment": _("Trainee enrollment"),
    "import_batch": _("Import batch"),
    "milestone": _("Milestone"),
    "notification_preferences": _("Notification preferences"),
    "project": _("Project"),
    "restore_test": _("Restore test"),
    "retention_inventory": _("Retention inventory"),
    "session": _("Session"),
    "tag": _("Tag"),
    "task": _("Task"),
    "trainer": _("Trainer"),
    "ai_briefing": _("AI project briefing"),
    "executive_report": _("CEO Telegram report"),
    "critical_task_alert": _("Critical task alert"),
    "agent_run": _("Project-agent run"),
}


def action_label(action_code: str) -> object:
    return ACTION_LABELS.get(action_code, action_code)


def target_type_label(target_type: str) -> object:
    return TARGET_TYPE_LABELS.get(target_type, target_type)
