# Generated by Django 5.2.16 on 2026-07-26 00:41

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 2-30 uppercase English letters, numbers, underscores, or hyphens, starting with a letter.",
                                regex="^[A-Z][A-Z0-9_-]{1,29}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="English name"),
                ),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=350),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("code",),
                "permissions": (
                    ("archive_category", "Can archive categories"),
                    ("restore_category", "Can restore categories"),
                ),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("code"),
                        name="projects_category_code_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("archived_at__isnull", True), ("is_archived", False)
                            ),
                            models.Q(
                                ("archived_at__isnull", False), ("is_archived", True)
                            ),
                            _connector="OR",
                        ),
                        name="projects_category_archive_state_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 2-30 uppercase English letters, numbers, underscores, or hyphens, starting with a letter.",
                                regex="^[A-Z][A-Z0-9_-]{1,29}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="English name"),
                ),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=350),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "ordering": ("code",),
                "permissions": (
                    ("archive_client", "Can archive clients"),
                    ("restore_client", "Can restore clients"),
                ),
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("code"),
                        name="projects_client_code_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("archived_at__isnull", True), ("is_archived", False)
                            ),
                            models.Q(
                                ("archived_at__isnull", False), ("is_archived", True)
                            ),
                            _connector="OR",
                        ),
                        name="projects_client_archive_state_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 2-30 uppercase English letters, numbers, underscores, or hyphens, starting with a letter.",
                                regex="^[A-Z][A-Z0-9_-]{1,29}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="English name"),
                ),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="priority",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="budget",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR",
                        editable=False,
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                ("goals", models.TextField(blank=True, verbose_name="goals")),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="requirements"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="archived by",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="projects.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="organizations.department",
                        verbose_name="department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="project manager",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervised_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="supervisor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
                "permissions": (
                    ("view_all_projects", "Can view all projects"),
                    ("view_managed_projects", "Can view managed projects"),
                    ("view_assigned_projects", "Can view assigned projects"),
                    ("view_project_budget", "Can view project budgets"),
                    ("manage_project_team", "Can manage project teams"),
                    ("view_project_history", "Can view project history"),
                    ("archive_project", "Can archive projects"),
                    ("restore_project", "Can restore projects"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="added_project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="removed_project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user_id", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="projects_project_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="projects_project_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget__isnull", True), ("budget__gte", 0), _connector="OR"
                ),
                name="projects_project_budget_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("draft", "active", "on_hold", "cancelled"))
                ),
                name="projects_project_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("priority__in", ("low", "medium", "high", "critical"))
                ),
                name="projects_project_priority_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "SAR")),
                name="projects_project_currency_sar",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                        ("is_archived", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                        ("is_archived", True),
                    ),
                    _connector="OR",
                ),
                name="projects_project_archive_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("supervisor__isnull", True),
                    models.Q(("manager", models.F("supervisor")), _negated=True),
                    _connector="OR",
                ),
                name="projects_project_manager_supervisor_distinct",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project", "removed_at"], name="projects_member_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("project", "user"),
                name="projects_membership_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("removed_at__isnull", True), ("removed_by__isnull", True)
                    ),
                    models.Q(
                        ("removed_at__isnull", False), ("removed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="projects_membership_removal_state_valid",
            ),
        ),
    ]
