# Generated by Django 5.2.16 on 2026-08-07 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_seed_phase2_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=255,
                        upload_to=apps.accounts.models.profile_avatar_upload_path,
                    ),
                ),
                ("content_sha256", models.CharField(editable=False, max_length=64)),
                ("source_size", models.PositiveIntegerField(editable=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deactivated_profile_avatars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_avatars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="acct_avatar_user_active_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user",),
                        name="accounts_one_active_avatar_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("deactivated_at__isnull", True), ("is_active", True)
                            ),
                            models.Q(
                                ("deactivated_at__isnull", False), ("is_active", False)
                            ),
                            _connector="OR",
                        ),
                        name="accounts_avatar_active_timestamp_consistent",
                    ),
                ],
            },
        ),
    ]
