# Generated by Django 5.2.16 on 2026-08-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0003_remove_project_projects_project_status_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")],
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                (
                    "detail_level",
                    models.CharField(
                        choices=[
                            ("executive", "Executive detail"),
                            ("operational", "Operational detail"),
                        ],
                        max_length=16,
                        verbose_name="detail level",
                    ),
                ),
                (
                    "evidence_window_days",
                    models.PositiveSmallIntegerField(
                        choices=[(7, "7 days"), (14, "14 days"), (30, "30 days")],
                        verbose_name="evidence window",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("provider_code", models.CharField(blank=True, max_length=24)),
                ("model_code", models.CharField(blank=True, max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                (
                    "input_fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("evidence_count", models.PositiveSmallIntegerField(default=0)),
                ("evidence_truncated", models.BooleanField(default=False)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cached_input_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_briefings",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_ai_briefings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_ai_briefings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "permissions": (
                    ("generate_aibriefing", "Can generate AI project briefings"),
                    ("review_aibriefing", "Can review AI project briefings"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AIBriefingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ref", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("task", "Task"),
                            ("milestone", "Milestone"),
                            ("approval", "Approval"),
                            ("audit", "Audit event"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_id", models.CharField(max_length=64)),
                ("source_label", models.CharField(max_length=250)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "briefing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="ai_briefings.aibriefing",
                    ),
                ),
            ],
            options={
                "ordering": ("source_type", "source_id"),
            },
        ),
        migrations.AddIndex(
            model_name="aibriefing",
            index=models.Index(
                fields=["project", "-created_at"], name="ai_brief_project_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aibriefing",
            index=models.Index(
                fields=["requested_by", "-created_at"], name="ai_brief_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ("ar", "en"))),
                name="ai_briefings_language_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(("detail_level__in", ("executive", "operational"))),
                name="ai_briefings_detail_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(("evidence_window_days__in", (7, 14, 30))),
                name="ai_briefings_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("queued", "processing", "completed", "failed"))
                ),
                name="ai_briefings_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("started_at__isnull", True),
                        ("status", "queued"),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("started_at__isnull", False),
                        ("status", "processing"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("started_at__isnull", False),
                        ("status__in", ("completed", "failed")),
                    ),
                    _connector="OR",
                ),
                name="ai_briefings_lifecycle_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reviewed_at__isnull", True), ("reviewed_by__isnull", True)
                    ),
                    models.Q(
                        ("reviewed_at__isnull", False), ("reviewed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="ai_briefings_review_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefingsource",
            constraint=models.UniqueConstraint(
                fields=("briefing", "source_ref"), name="ai_briefings_source_ref_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="aibriefingsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        ("project", "task", "milestone", "approval", "audit"),
                    )
                ),
                name="ai_briefings_source_type_valid",
            ),
        ),
    ]
