# Generated by Django 5.2.16 on 2026-08-04 14:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0003_remove_project_projects_project_status_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentIntegrationNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_summary", models.JSONField(default=dict)),
                ("citations", models.JSONField(default=list)),
                ("reviewed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_memories",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_agent_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-reviewed_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="AgentReviewedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("safe_payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("acknowledged", "Acknowledged"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("lease_token_hash", models.CharField(blank=True, max_length=64)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                ("callback_code", models.CharField(blank=True, max_length=32)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "memory",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_event",
                        to="project_agents.agentmemory",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_code",
                    models.CharField(
                        choices=[("project_recovery", "Project recovery plan")],
                        max_length=32,
                    ),
                ),
                ("optional_context", models.CharField(blank=True, max_length=500)),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")], max_length=2
                    ),
                ),
                ("provider_code", models.CharField(blank=True, max_length=24)),
                ("model_code", models.CharField(max_length=80)),
                (
                    "prompt_version",
                    models.CharField(default="phase17-v1", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("planning", "Planning"),
                            ("running", "Running"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("executing", "Executing"),
                            ("verifying", "Verifying"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("stale", "Stale"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=0)),
                ("max_steps", models.PositiveSmallIntegerField(default=8)),
                ("max_total_tokens", models.PositiveIntegerField(default=16000)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("cached_input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("input_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("verification_data", models.JSONField(blank=True, default=dict)),
                ("safe_failure_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requester",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": (
                    ("start_agentrun", "Can start project agent runs"),
                    ("review_agentrun", "Can review completed project agent runs"),
                    ("approve_agentproposal", "Can approve project agent proposals"),
                    ("execute_agentproposal", "Can execute approved agent proposals"),
                ),
            },
        ),
        migrations.AddField(
            model_name="agentmemory",
            name="source_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memory",
                to="project_agents.agentrun",
            ),
        ),
        migrations.CreateModel(
            name="AgentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("tool", "Tool"),
                            ("observation", "Observation"),
                            ("proposal", "Proposal"),
                            ("final", "Final"),
                            ("verification", "Verification"),
                        ],
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=16,
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="project_agents.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
            },
        ),
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_code",
                    models.CharField(
                        choices=[
                            ("propose_task_update", "Task update"),
                            ("propose_task_assignment", "Task assignment"),
                            ("propose_task_comment", "Task comment"),
                            ("propose_deadline_change", "Deadline change"),
                            ("propose_team_notification", "Team notification"),
                        ],
                        max_length=48,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("citations", models.JSONField(default=list)),
                ("before_state", models.JSONField(default=dict)),
                ("before_state_fingerprint", models.CharField(max_length=64)),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("executed", "Executed"),
                            ("stale", "Stale"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_idempotency_key",
                    models.CharField(max_length=64, unique=True),
                ),
                ("execution_result", models.JSONField(blank=True, default=dict)),
                ("safe_failure_code", models.CharField(blank=True, max_length=64)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_agent_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="project_agents.agentrun",
                    ),
                ),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposal",
                        to="project_agents.agentstep",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="AgentToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_code", models.CharField(max_length=48)),
                ("arguments", models.JSONField(default=dict)),
                ("safe_result", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("safe_failure_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_calls",
                        to="project_agents.agentrun",
                    ),
                ),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_call",
                        to="project_agents.agentstep",
                    ),
                ),
            ],
            options={
                "ordering": ("step__sequence",),
            },
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["project", "-created_at"], name="agent_run_project_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrun",
            index=models.Index(
                fields=["requester", "-created_at"], name="agent_run_user_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("goal_code", "project_recovery")),
                name="project_agents_goal_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("language__in", ("ar", "en"))),
                name="project_agents_language_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_steps__gte", 1), ("max_steps__lte", 8)),
                name="project_agents_steps_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_step__lte", models.F("max_steps"))),
                name="project_agents_current_step_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reviewed_at__isnull", True), ("reviewed_by__isnull", True)
                    ),
                    models.Q(
                        ("reviewed_at__isnull", False), ("reviewed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="project_agents_review_state_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["project", "-reviewed_at"], name="agent_memory_proj_rev_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="project_agents_step_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1), ("sequence__lte", 8)),
                name="project_agents_step_sequence_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approver__isnull", True),
                        ("decided_at__isnull", True),
                        ("decision_reason", ""),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("approver__isnull", False),
                        ("decided_at__isnull", False),
                        (
                            "status__in",
                            (
                                "approved",
                                "rejected",
                                "executing",
                                "executed",
                                "stale",
                                "failed",
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="project_agents_proposal_decision_valid",
            ),
        ),
    ]
