# Generated by Django 5.2.16 on 2026-08-04 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_agents", "0002_seed_phase17_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agentproposal",
            name="project_agents_proposal_decision_valid",
        ),
        migrations.AlterField(
            model_name="agentproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("executing", "Executing"),
                    ("executed", "Executed"),
                    ("stale", "Stale"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="agentproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("approver__isnull", True),
                        ("decided_at__isnull", True),
                        ("decision_reason", ""),
                        ("status__in", ("pending", "expired")),
                    ),
                    models.Q(
                        ("approver__isnull", False),
                        ("decided_at__isnull", False),
                        (
                            "status__in",
                            (
                                "approved",
                                "rejected",
                                "executing",
                                "executed",
                                "stale",
                                "failed",
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="project_agents_proposal_decision_valid",
            ),
        ),
    ]
