# Generated by Django 5.2.16 on 2026-08-04 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_agents", "0004_agentintegrationnonce_expiry"),
        ("projects", "0003_remove_project_projects_project_status_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agentproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "action_code__in",
                        (
                            "propose_task_update",
                            "propose_task_assignment",
                            "propose_task_comment",
                            "propose_deadline_change",
                            "propose_team_notification",
                        ),
                    )
                ),
                name="project_agents_proposal_action_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("risk__in", ("low", "medium", "high"))),
                name="project_agents_proposal_risk_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentreviewedevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("acknowledged_at__isnull", True),
                        ("callback_code", ""),
                        ("lease_token_hash", ""),
                        ("leased_until__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("acknowledged_at__isnull", True),
                        ("callback_code", ""),
                        ("leased_until__isnull", False),
                        ("status", "leased"),
                        models.Q(("lease_token_hash", ""), _negated=True),
                    ),
                    models.Q(
                        ("acknowledged_at__isnull", False),
                        ("callback_code__in", ("notified", "archived", "rejected")),
                        ("lease_token_hash", ""),
                        ("leased_until__isnull", True),
                        ("status", "acknowledged"),
                    ),
                    models.Q(
                        ("acknowledged_at__isnull", False),
                        ("callback_code", "failed"),
                        ("lease_token_hash", ""),
                        ("leased_until__isnull", True),
                        ("status", "failed"),
                    ),
                    _connector="OR",
                ),
                name="project_agents_event_lifecycle_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "queued",
                            "planning",
                            "running",
                            "awaiting_approval",
                            "executing",
                            "verifying",
                            "completed",
                            "failed",
                            "cancelled",
                            "expired",
                            "stale",
                        ),
                    )
                ),
                name="project_agents_run_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("model_code__in", ("openai/gpt-oss-20b", "openai/gpt-oss-120b"))
                ),
                name="project_agents_model_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "step_type__in",
                        (
                            "plan",
                            "tool",
                            "observation",
                            "proposal",
                            "final",
                            "verification",
                        ),
                    )
                ),
                name="project_agents_step_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentstep",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("pending", "running", "completed", "failed", "cancelled"),
                    )
                ),
                name="project_agents_step_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agenttoolcall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tool_code__in",
                        (
                            "get_project_snapshot",
                            "list_overdue_and_blocked_tasks",
                            "get_upcoming_milestones",
                            "get_pending_approvals",
                            "get_team_workload",
                            "calculate_project_progress",
                            "recall_reviewed_agent_runs",
                        ),
                    )
                ),
                name="project_agents_tool_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="agenttoolcall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "running", "completed", "failed"))
                ),
                name="project_agents_tool_status_valid",
            ),
        ),
    ]
