# Generated by Django 5.2.16 on 2026-07-29 03:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0003_remove_course_courses_course_status_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="preview",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("valid_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_trainee_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainee_imports",
                        to="courses.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainee_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "permissions": (
                    ("import_trainees", "Can preview trainee imports"),
                    ("confirm_trainee_import", "Can confirm trainee imports"),
                    ("view_import_history", "Can view trainee import history"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="full name"),
                ),
                ("phone", models.CharField(max_length=40, verbose_name="phone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "name_key",
                    models.CharField(db_index=True, editable=False, max_length=300),
                ),
                (
                    "phone_key",
                    models.CharField(db_index=True, editable=False, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_trainees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_trainees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("full_name", "pk"),
                "permissions": (
                    ("view_trainee_contact", "Can view trainee contact data"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trainee_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="trainee number",
                    ),
                ),
                ("identity_key", models.CharField(editable=False, max_length=340)),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainee_enrollments",
                        to="courses.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_enrollments",
                        to="trainees.trainee",
                    ),
                ),
            ],
            options={
                "ordering": ("course_id", "trainee_number"),
                "permissions": (
                    ("archive_enrollment", "Can archive trainee enrollments"),
                    ("restore_enrollment", "Can restore trainee enrollments"),
                    ("view_all_enrollments", "Can view all trainee enrollments"),
                    (
                        "view_managed_enrollments",
                        "Can view managed trainee enrollments",
                    ),
                    ("view_roster_enrollments", "Can view limited course rosters"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("full_name", models.CharField(blank=True, max_length=250)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("identity_key", models.CharField(blank=True, max_length=340)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("duplicate", "Duplicate"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("create", "Create"),
                            ("skip", "Skip"),
                            ("update", "Update"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="trainees.importbatch",
                    ),
                ),
                (
                    "created_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_import_rows",
                        to="trainees.courseenrollment",
                    ),
                ),
                (
                    "duplicate_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicate_import_rows",
                        to="trainees.courseenrollment",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"),
                        name="trainees_import_row_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("course", "trainee_number"),
                name="trainees_course_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(
                fields=("course", "identity_key"),
                name="trainees_course_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("trainee_number__gt", 0)),
                name="trainees_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                        ("is_archived", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                        ("is_archived", True),
                    ),
                    _connector="OR",
                ),
                name="trainees_enrollment_archive_valid",
            ),
        ),
    ]
