# Generated by Django 5.2.16 on 2026-07-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainees", "0002_seed_phase8_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="warning_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="importrow",
            name="classification",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("warning", "Warning"),
                    ("duplicate", "Duplicate"),
                    ("error", "Error"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
