# Generated by Django 5.2.16 on 2026-07-29 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_course_courses_course_status_valid_and_more"),
        ("trainees", "0003_importbatch_warning_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("identity_key", ""), _negated=True),
                name="trainees_identity_key_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("preview", "confirmed", "cancelled"))
                ),
                name="trainees_import_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmed_at__isnull", False),
                        ("confirmed_by__isnull", False),
                        ("status", "confirmed"),
                    ),
                    models.Q(
                        ("confirmed_at__isnull", True),
                        ("confirmed_by__isnull", True),
                        ("status__in", ("preview", "cancelled")),
                    ),
                    _connector="OR",
                ),
                name="trainees_import_confirmation_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("classification__in", ("valid", "warning", "duplicate", "error"))
                ),
                name="trainees_import_row_class_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resolution__in", ("", "create", "skip", "update"))
                ),
                name="trainees_import_row_resolution_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainee",
            constraint=models.CheckConstraint(
                condition=models.Q(("name_key", ""), _negated=True),
                name="trainees_name_key_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainee",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone_key", ""), _negated=True),
                name="trainees_phone_key_not_blank",
            ),
        ),
    ]
