# Generated by Django 5.2.16 on 2026-07-27 00:27

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import apps.courses.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_seed_phase3_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 2-30 uppercase English letters, numbers, underscores, or hyphens, starting with a letter.",
                                regex="^[A-Z][A-Z0-9_-]{1,29}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="English name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In person"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=16,
                        verbose_name="delivery type",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="location"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="capacity",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="starts at")),
                ("end_at", models.DateTimeField(verbose_name="ends at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=800),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
                "permissions": (
                    ("view_all_courses", "Can view all courses"),
                    ("view_managed_courses", "Can view managed courses"),
                    ("view_assigned_courses", "Can view assigned courses"),
                    ("archive_course", "Can archive courses"),
                    ("restore_course", "Can restore courses"),
                    ("manage_course_trainers", "Can manage course trainers"),
                    ("upload_course_file", "Can upload course files"),
                    ("view_course_history", "Can view course history"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CourseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        upload_to=apps.courses.models.course_file_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=150)),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="courses.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_course_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 2-30 uppercase English letters, numbers, underscores, or hyphens, starting with a letter.",
                                regex="^[A-Z][A-Z0-9_-]{1,29}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, verbose_name="English name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="phone"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organization"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=700),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="archived at"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_trainers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_trainers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_trainers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
                "permissions": (
                    ("archive_trainer", "Can archive trainers"),
                    ("restore_trainer", "Can restore trainers"),
                    ("view_trainer_contact", "Can view trainer contact data"),
                ),
            },
        ),
        migrations.CreateModel(
            name="CourseTrainerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_course_trainers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="removed_course_trainers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_assignments",
                        to="courses.trainer",
                    ),
                ),
            ],
            options={
                "ordering": ("trainer_id", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="courses_course_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="courses_course_schedule_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)),
                name="courses_course_capacity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("draft", "active", "on_hold", "cancelled"))
                ),
                name="courses_course_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_type__in", ("in_person", "online", "hybrid"))
                ),
                name="courses_course_delivery_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_type", "online"),
                    models.Q(("location", ""), _negated=True),
                    _connector="OR",
                ),
                name="courses_course_location_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                        ("is_archived", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                        ("is_archived", True),
                    ),
                    _connector="OR",
                ),
                name="courses_course_archive_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="courses_trainer_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="courses_trainer_email_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                        ("is_archived", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                        ("is_archived", True),
                    ),
                    _connector="OR",
                ),
                name="courses_trainer_archive_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursetrainerassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("removed_at__isnull", True)),
                fields=("course", "trainer"),
                name="courses_assignment_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursetrainerassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("removed_at__isnull", True), ("removed_by__isnull", True)
                    ),
                    models.Q(
                        ("removed_at__isnull", False), ("removed_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="courses_assignment_removal_state_valid",
            ),
        ),
    ]
