# Generated by Django 5.2.16 on 2026-07-28 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_seed_phase4_permissions"),
        ("projects", "0002_seed_phase3_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="courses_course_status_valid",
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ("draft", "active", "on_hold", "cancelled", "completed"),
                    )
                ),
                name="courses_course_status_valid",
            ),
        ),
    ]
