# Generated by Django 5.2.16 on 2026-07-28 12:25

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0002_seed_phase4_permissions"),
        ("projects", "0002_seed_phase3_permissions"),
        ("tasks", "0002_seed_phase5_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("course", "Course"),
                            ("milestone", "Milestone"),
                            ("project", "Project"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="target type",
                    ),
                ),
                ("attempt", models.PositiveIntegerField(verbose_name="attempt")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_supervisor", "Pending Supervisor"),
                            ("pending_manager", "Pending Project Manager"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_supervisor",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="courses.course",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-submitted_at", "-pk"),
                "permissions": (
                    ("view_all_approvals", "Can view all approvals"),
                    ("view_managed_approvals", "Can view managed approvals"),
                    ("view_context_approvals", "Can view context approvals"),
                    ("view_own_approvals", "Can view own approvals"),
                    ("submit_approval", "Can submit completion approval"),
                    ("decide_supervisor_approval", "Can decide Supervisor approval"),
                    ("decide_manager_approval", "Can decide Project Manager approval"),
                ),
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="sequence")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("supervisor", "Supervisor"),
                            ("project_manager", "Project Manager"),
                        ],
                        max_length=24,
                        verbose_name="role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="steps",
                        to="approvals.approvalrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                        verbose_name="outcome",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="reason")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="approvals.approvalstep",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "pk"),
                "default_permissions": ("view",),
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use 2-30 uppercase English letters, numbers, underscores, or hyphens, starting with a letter.",
                                regex="^[A-Z][A-Z0-9_-]{1,29}$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=250, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=250, verbose_name="English name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("pending_approval", "Pending approval"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="status",
                    ),
                ),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=700),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("project__code", "due_date", "code"),
                "permissions": (
                    ("view_all_milestones", "Can view all milestones"),
                    ("view_managed_milestones", "Can view managed milestones"),
                    ("view_context_milestones", "Can view context milestones"),
                    ("archive_milestone", "Can archive milestones"),
                    ("restore_milestone", "Can restore milestones"),
                ),
            },
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="approvals.milestone",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalstep",
            constraint=models.UniqueConstraint(
                fields=("request", "sequence"), name="approvals_step_sequence_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalstep",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__in", (1, 2))),
                name="approvals_step_sequence_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="approvals_milestone_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(("due_date__gte", models.F("start_date"))),
                name="approvals_milestone_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "draft",
                            "in_progress",
                            "pending_approval",
                            "completed",
                            "cancelled",
                        ),
                    )
                ),
                name="approvals_milestone_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                        ("is_archived", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                        ("is_archived", True),
                    ),
                    _connector="OR",
                ),
                name="approvals_milestone_archive_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", True),
                        ("milestone__isnull", True),
                        ("project__isnull", True),
                        ("target_type", "task"),
                        ("task__isnull", False),
                    ),
                    models.Q(
                        ("course__isnull", False),
                        ("milestone__isnull", True),
                        ("project__isnull", True),
                        ("target_type", "course"),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("milestone__isnull", False),
                        ("project__isnull", True),
                        ("target_type", "milestone"),
                        ("task__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("milestone__isnull", True),
                        ("project__isnull", False),
                        ("target_type", "project"),
                        ("task__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="approvals_request_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gt", 0)),
                name="approvals_request_attempt_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("task__isnull", False)),
                fields=("task", "attempt"),
                name="approvals_task_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("course__isnull", False)),
                fields=("course", "attempt"),
                name="approvals_course_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("milestone__isnull", False)),
                fields=("milestone", "attempt"),
                name="approvals_milestone_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("project", "attempt"),
                name="approvals_project_attempt_unique",
            ),
        ),
    ]
