# Generated by Django 5.2.16 on 2026-07-29 15:42

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("search", "Global search"),
                            ("kanban", "Kanban"),
                            ("calendar", "Calendar"),
                            ("timeline", "Timeline"),
                            ("gantt", "Gantt"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="view",
                    ),
                ),
                ("criteria", models.JSONField(default=dict, verbose_name="criteria")),
                (
                    "schema_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("view_type", "name", "pk"),
                "constraints": [
                    models.UniqueConstraint(
                        models.F("owner"),
                        models.F("view_type"),
                        django.db.models.functions.text.Lower("name"),
                        name="workspace_filter_owner_view_name_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 1)),
                        name="workspace_filter_schema_v1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "view_type__in",
                                ("search", "kanban", "calendar", "timeline", "gantt"),
                            )
                        ),
                        name="workspace_filter_view_valid",
                    ),
                ],
            },
        ),
    ]
