# Generated by Django 5.2.16 on 2026-07-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.attendance.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0003_remove_course_courses_course_status_valid_and_more"),
        ("trainees", "0004_courseenrollment_trainees_identity_key_not_blank_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("pending_review", "Pending supervisor review")],
                        default="pending_review",
                        max_length=24,
                        verbose_name="state",
                    ),
                ),
                (
                    "trainer_notes",
                    models.TextField(blank=True, verbose_name="trainer notes"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.CreateModel(
            name="AttendanceEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        upload_to=apps.attendance.models.evidence_upload_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=150)),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="attendance.attendancesubmission",
                    ),
                ),
            ],
            options={
                "ordering": ("uploaded_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Arabic title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="English title"),
                ),
                (
                    "start_at",
                    models.DateTimeField(db_index=True, verbose_name="starts at"),
                ),
                ("end_at", models.DateTimeField(verbose_name="ends at")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("occurrence_index", models.PositiveIntegerField(default=1)),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="archived"
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="archived_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurrence_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_sessions",
                        to="attendance.session",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="courses.trainer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("start_at", "pk"),
                "permissions": (
                    ("manage_all_sessions", "Can manage all sessions"),
                    (
                        "manage_managed_sessions",
                        "Can manage sessions in managed courses",
                    ),
                    ("view_context_sessions", "Can view active context sessions"),
                    ("archive_session", "Can archive sessions"),
                    ("issue_trainer_link", "Can issue trainer links"),
                ),
            },
        ),
        migrations.AddField(
            model_name="attendancesubmission",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_submission",
                to="attendance.session",
            ),
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_participations",
                        to="trainees.courseenrollment",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="attendance.session",
                    ),
                ),
            ],
            options={
                "ordering": ("enrollment__trainee_number",),
            },
        ),
        migrations.CreateModel(
            name="AttendanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=16,
                        verbose_name="attendance",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=500, verbose_name="notes"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="attendance.attendancesubmission",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_entries",
                        to="attendance.sessionparticipant",
                    ),
                ),
            ],
            options={
                "ordering": ("participant__enrollment__trainee_number",),
            },
        ),
        migrations.CreateModel(
            name="TrainerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("submitted", "Submitted"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="state",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_trainer_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trainer_links",
                        to="attendance.session",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at", "-pk"),
            },
        ),
        migrations.AddField(
            model_name="attendancesubmission",
            name="trainer_link",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission",
                to="attendance.trainerlink",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="attendance_session_schedule_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrence_index__gt", 0)),
                name="attendance_occurrence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurrence_source__isnull", False)),
                fields=("recurrence_source", "occurrence_index"),
                name="attendance_recurrence_occurrence_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("archived_at__isnull", True),
                        ("archived_by__isnull", True),
                        ("is_archived", False),
                    ),
                    models.Q(
                        ("archived_at__isnull", False),
                        ("archived_by__isnull", False),
                        ("is_archived", True),
                    ),
                    _connector="OR",
                ),
                name="attendance_session_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                fields=("session", "enrollment"),
                name="attendance_session_participant_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceentry",
            constraint=models.UniqueConstraint(
                fields=("submission", "participant"),
                name="attendance_submission_participant_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendanceentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("value__in", ("present", "absent", "late", "excused"))
                ),
                name="attendance_entry_value_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainerlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ("active", "submitted", "revoked"))),
                name="attendance_link_state_valid",
            ),
        ),
    ]
