# Generated by Django 5.2.16 on 2026-07-29 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_seed_phase9_permissions"),
        ("courses", "0003_remove_course_courses_course_status_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("course", "trainer", "start_at"),
                name="attendance_session_start_unique",
            ),
        ),
    ]
