# Generated by Django 5.2.16 on 2026-07-29 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_session_attendance_session_start_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(max_length=1000, verbose_name="correction reason"),
                ),
                ("before_snapshot", models.JSONField(default=list)),
                ("after_snapshot", models.JSONField(default=list)),
                (
                    "corrected_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={"ordering": ("corrected_at", "pk")},
        ),
        migrations.CreateModel(
            name="AttendanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=16,
                        verbose_name="decision",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="reason"
                    ),
                ),
                ("entry_snapshot", models.JSONField(default=list)),
                ("trainer_notes_snapshot", models.TextField(blank=True)),
                (
                    "decided_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={"ordering": ("attempt", "pk")},
        ),
        migrations.AlterModelOptions(
            name="attendancesubmission",
            options={
                "ordering": ("-submitted_at",),
                "permissions": (
                    ("review_attendance", "Can review supervised attendance"),
                    ("view_all_attendance", "Can view all attendance"),
                    ("view_managed_attendance", "Can view managed attendance"),
                    ("view_supervised_attendance", "Can view supervised attendance"),
                    ("correct_all_attendance", "Can correct all attendance"),
                    ("correct_managed_attendance", "Can correct managed attendance"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="attendancesubmission",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending supervisor review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending_review",
                max_length=24,
                verbose_name="state",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ("pending_review", "approved", "rejected"))
                ),
                name="attendance_submission_state_valid",
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="corrected_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrections",
                to="attendance.attendancesubmission",
            ),
        ),
        migrations.AddField(
            model_name="attendancereview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancereview",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="attendance.attendancesubmission",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason", ""), _negated=True),
                name="attendance_correction_reason_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancereview",
            constraint=models.UniqueConstraint(
                fields=("submission", "attempt"),
                name="attendance_review_attempt_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancereview",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision__in", ("approved", "rejected"))),
                name="attendance_review_decision_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancereview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("decision", "approved"), ("reason", "")),
                    models.Q(
                        ("decision", "rejected"),
                        models.Q(("reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="attendance_review_reason_valid",
            ),
        ),
    ]
