# Generated by Django 5.2.16 on 2026-07-25.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_phase2_account_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="action",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        max_length=64,
                        verbose_name="target type",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="target ID",
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="target label",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        verbose_name="metadata",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="correlation ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="created at",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "ordering": ("-created_at", "-pk"),
                "default_permissions": ("view",),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_target_lookup_idx",
                    )
                ],
            },
        )
    ]
