# Generated by Django 5.2.16 on 2026-07-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0006_alter_auditevent_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="scope",
            field=models.CharField(
                choices=[
                    ("security", "Security"),
                    ("projects", "Projects"),
                    ("courses", "Courses"),
                    ("tasks", "Tasks"),
                    ("approvals", "Approvals"),
                    ("trainees", "Trainees"),
                    ("attendance", "Attendance"),
                ],
                db_index=True,
                default="security",
                max_length=32,
                verbose_name="scope",
            ),
        ),
    ]
