# Generated by Django 5.2.16 on 2026-07-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("export_project_progress", "Can export project progress reports"),
                    ("export_overdue_tasks", "Can export overdue task reports"),
                    (
                        "export_course_attendance",
                        "Can export course attendance reports",
                    ),
                    (
                        "export_project_attendance",
                        "Can export project attendance reports",
                    ),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
