# Generated by Django 5.2.16 on 2026-08-04 12:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0002_seed_phase5_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="N8nRequestNonce",
            fields=[
                (
                    "digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("expires_at",),
            },
        ),
        migrations.CreateModel(
            name="CriticalTaskAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("message_ar", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("delivered", "Delivered"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("lease_digest", models.CharField(blank=True, max_length=64)),
                (
                    "lease_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="critical_telegram_alerts",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "lease_expires_at"],
                        name="critical_alert_lease_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ("pending", "leased", "delivered"))
                        ),
                        name="critical_alert_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("lease_digest", ""),
                                ("lease_expires_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("delivered_at__isnull", True),
                                ("lease_digest__gt", ""),
                                ("lease_expires_at__isnull", False),
                                ("status", "leased"),
                            ),
                            models.Q(
                                ("delivered_at__isnull", False),
                                ("lease_digest", ""),
                                ("lease_expires_at__isnull", True),
                                ("status", "delivered"),
                            ),
                            _connector="OR",
                        ),
                        name="critical_alert_lifecycle_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveReportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("current_tasks", "Current tasks"),
                            ("overdue_tasks", "Overdue tasks"),
                            ("attendance", "Trainee attendance"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "window_days",
                    models.PositiveSmallIntegerField(
                        choices=[(7, "7 days"), (14, "14 days"), (30, "30 days")]
                    ),
                ),
                ("chat_id_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("provider_code", models.CharField(blank=True, max_length=24)),
                ("model_code", models.CharField(blank=True, max_length=80)),
                ("prompt_version", models.CharField(blank=True, max_length=32)),
                ("source_count", models.PositiveSmallIntegerField(default=0)),
                ("source_truncated", models.BooleanField(default=False)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cached_input_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executive_report_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "permissions": (
                    ("request_executivereport", "Can request CEO Telegram reports"),
                    ("receive_critical_alert", "Can receive CEO critical task alerts"),
                ),
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-created_at"],
                        name="exec_report_user_created_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "report_type__in",
                                ("current_tasks", "overdue_tasks", "attendance"),
                            )
                        ),
                        name="exec_report_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("window_days__in", (7, 14, 30))),
                        name="exec_report_window_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ("queued", "processing", "completed", "failed"),
                            )
                        ),
                        name="exec_report_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", True),
                                ("status", "queued"),
                            ),
                            models.Q(
                                ("completed_at__isnull", True),
                                ("started_at__isnull", False),
                                ("status", "processing"),
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("started_at__isnull", False),
                                ("status__in", ("completed", "failed")),
                            ),
                            _connector="OR",
                        ),
                        name="exec_report_lifecycle_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("downloaded_at__isnull", True),
                            models.Q(
                                ("downloaded_at__isnull", False),
                                ("status", "completed"),
                            ),
                            _connector="OR",
                        ),
                        name="exec_report_download_state_valid",
                    ),
                ],
            },
        ),
    ]
