# Generated by Django 5.2.16 on 2026-07-25.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Use 2-20 uppercase English letters, numbers, "
                                    "underscores, or hyphens, starting with a letter."
                                ),
                                regex="^[A-Z][A-Z0-9_-]*$",
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=150, verbose_name="Arabic name"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=150, verbose_name="English name"),
                ),
                (
                    "search_key",
                    models.CharField(db_index=True, editable=False, max_length=350),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="archived",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="archived at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ("code",),
                "permissions": (
                    ("archive_department", "Can archive departments"),
                    ("restore_department", "Can restore departments"),
                    ("view_all_departments", "Can view all active departments"),
                ),
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(is_archived=False, archived_at__isnull=True)
                            | models.Q(is_archived=True, archived_at__isnull=False)
                        ),
                        name="organizations_department_archive_state_valid",
                    )
                ],
            },
        )
    ]
