# Generated by Django 5.2.16 on 2026-07-29 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("task_assignment", "Task assignments"),
                            ("approval", "Approvals"),
                            ("deadline", "Deadlines and overdue"),
                            ("mention", "Mentions"),
                        ],
                        db_index=True,
                        max_length=24,
                        verbose_name="category",
                    ),
                ),
                ("message_code", models.CharField(max_length=32)),
                ("event_key", models.CharField(max_length=200)),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("body_ar", models.TextField()),
                ("body_en", models.TextField()),
                ("target_path", models.CharField(blank=True, max_length=500)),
                (
                    "show_in_app",
                    models.BooleanField(default=True),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        verbose_name="read",
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("retry", "Retry scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_code",
                    models.CharField(blank=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ("next_attempt_at", "pk"),
                "permissions": (
                    (
                        "view_delivery_status",
                        "Can view notification delivery status",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("task_assignment", "Task assignments"),
                            ("approval", "Approvals"),
                            ("deadline", "Deadlines and overdue"),
                            ("mention", "Mentions"),
                        ],
                        max_length=24,
                        verbose_name="category",
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="In-app notifications",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email notifications",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("category",),
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "event_key"),
                name="notifications_recipient_event_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        ("task_assignment", "approval", "deadline", "mention"),
                    )
                ),
                name="notifications_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_read", False), ("read_at__isnull", True)),
                    models.Q(("is_read", True), ("read_at__isnull", False)),
                    _connector="OR",
                ),
                name="notifications_read_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "processing", "retry", "sent", "failed"))
                ),
                name="notifications_delivery_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("sent_at__isnull", False), ("status", "sent")),
                    models.Q(
                        models.Q(("status", "sent"), _negated=True),
                        ("sent_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="notifications_delivery_sent_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("recipient", "category"),
                name="notifications_preference_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        ("task_assignment", "approval", "deadline", "mention"),
                    )
                ),
                name="notifications_preference_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("category", "approval"), _negated=True),
                    ("in_app_enabled", True),
                    _connector="OR",
                ),
                name="notifications_approval_in_app_required",
            ),
        ),
    ]
