# Generated by Django 5.2.16 on 2026-08-04 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0003_remove_notification_notifications_category_valid_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notifications_category_valid",
        ),
        migrations.RemoveConstraint(
            model_name="notificationpreference",
            name="notifications_preference_category_valid",
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("task_assignment", "Task assignments"),
                    ("approval", "Approvals"),
                    ("deadline", "Deadlines and overdue"),
                    ("mention", "Mentions"),
                    ("ai_briefing", "AI project briefings"),
                    ("project_agent", "Project recovery agent"),
                ],
                db_index=True,
                max_length=24,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="category",
            field=models.CharField(
                choices=[
                    ("task_assignment", "Task assignments"),
                    ("approval", "Approvals"),
                    ("deadline", "Deadlines and overdue"),
                    ("mention", "Mentions"),
                    ("ai_briefing", "AI project briefings"),
                    ("project_agent", "Project recovery agent"),
                ],
                max_length=24,
                verbose_name="category",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        (
                            "task_assignment",
                            "approval",
                            "deadline",
                            "mention",
                            "ai_briefing",
                            "project_agent",
                        ),
                    )
                ),
                name="notifications_category_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        (
                            "task_assignment",
                            "approval",
                            "deadline",
                            "mention",
                            "ai_briefing",
                            "project_agent",
                        ),
                    )
                ),
                name="notifications_preference_category_valid",
            ),
        ),
    ]
