# Generated by Django 5.2.16 on 2026-08-04 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0004_remove_notification_notifications_category_valid_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notificationpreference",
            name="notifications_approval_in_app_required",
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category__in", ("approval", "project_agent")), _negated=True
                    ),
                    ("in_app_enabled", True),
                    _connector="OR",
                ),
                name="notifications_approval_in_app_required",
            ),
        ),
    ]
